---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/lookbook.md
  label: Lookbook
- type: document
  path: src/projects.md
  label: Projects
- type: document
  path: src/_data/settings.json
  label: Settings
- type: document
  path: src/material.md
  label: Material
- type: document
  path: src/plants.md
  label: Plants
- type: document
  path: src/flowes.md
  label: Flowers
- type: document
  path: src/index.md
  label: Home
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
