---
label: Settings
hide_body: true
fields:
- type: field_group
  name: meta
  label: meta
  fields:
  - type: text
    name: title
    label: title
  - type: text
    name: description
    label: description
  - type: text
    name: siteUrl
    label: siteUrl
  - type: text
    name: siteName
    label: siteName
  - type: file
    name: imgSrc
    label: imgSrc
  - type: text
    name: imgAtl
    label: imgAtl
- type: field_group
  name: header
  label: header
  fields:
  - type: file
    name: logo
    label: logo
  - type: field_group_list
    name: menu
    label: menu
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: url
      label: url
  - type: field_group_list
    name: socials
    label: socials
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: url
      label: url
    - type: text
      name: icon
      label: icon
- type: field_group_list
  name: footer
  label: footer
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: text
    label: text
- type: text
  name: cloudinary_url
  label: cloudinary_url
